### ISSUE TITLE
Instance for sprite:<mytheme> not working

### ISSUE THREAD

**Issue by ezequielalba** [magekey/magento2-grunt-sprite#2]
Hi!

I am testing this in a project to generate sprites for a magento2 theme, but after following the complete steps in your readme file, I have these results on the console after 'grunt sprite:customtheme' 

`Running "sprite:customtheme" (sprite) task
Verifying property sprite.customtheme exists in config...ERROR
>> Unable to process task.
Warning: Required config property "sprite.customtheme" missing. Use --force to continue.`

Any ideas?

Tried with the grunt sprite without theme to see, and says:

`No "sprite" targets found.`

grunt-sprite-config.json has the same structure as your demo but with different naming, that is all. 

Let me know!

Thank you so much!

**Comment by magekey** [comment]
The tool assumes installation through the composer. 
Take a look at **configs/path.js** 
`project: fs.realpathSync('../../../')`

To avoid a composer you can just clone the repo under the project root. 
Here is example. 
 - clone repo to **<project_root>/grunt-sprite** folder.
 - change a **project** path in the **configs/path.js** to 
`project: fs.realpathSync('../')`
 - add sprites to **configs/sprite.js** (create a new file)
```
module.exports = {
  sprite: {
  	//sprite configs
  }
};
```
 Hope this helps.

**Comment by ezequielalba** [comment]
It is installed via Composer and has the grunt setup done with the symlink to the project root, perhaps that is the issue? Let me test with creating the configs/sprite.js inside that symlinked folder and see. 

[UPDATE]
Yes, it looks for sprite.js as configs, but it breaks looking for variables that aren't on the same file, like project variable not defined, then looks for fs require, etc. Going to install it without composer and try again. 

Still, no luck. 

This is my sprite.js:

`module.exports = {
    sprite: {
        mytheme: {
            src: "../app/design/frontend/Vendor/mytheme/web/images/sprite/*.png",
            dest: "../app/design/frontend/Vendor/mytheme/web/images/sprite.png",
            padding: 10,
            destCss: "../app/design/frontend/Vendor/mytheme/web/css/source/_sprite.less",
            cssTemplate: "/templates/less.template.handlebars",
        }
    }
};`

Steps I did:
- Removed and reinstall via composer, configured without symlink and the same path that has since the start, created a new grunt-sprite-config.json with the configs from the Readme file, same result as the first post.
- Removed via composer, created the new folder, cloned the repo, created the new sprites config as pasted before in the post, still errors with the configs.

**Comment by ezequielalba** [comment]
Any ideas?

**Comment by magekey** [comment]
Unfortunately no. Could you help me to debug the tool and send more information about the error, so I could fix the issue in the next release?

**Comment by ezequielalba** [comment]
Yeah sure, tell me the steps or the data that you need from my implementation in order to help you!

**Comment by tigerofasia** [comment]
I'm having the same issue as @ezequielalba 

Any update on this @magekey ? 

Cheers!

**Comment by magekey** [comment]
@tigerofasia 
Make sure you updated config file with <mytheme> sprite. 
Just FYI: <mytheme> it's not a magento theme name, it's just a name of sprite defined in sprite.js.

**Comment by tigerofasia** [comment]
@magekey I think I've fixed it. There's an issue with this file `vendor/magekey/grunt-sprite/Gruntfile.js` in line ~19

I modified the code inside the try statement from this:

`return require(config.path.project + '/' +config.path.userConfigFile)`

to this:

`return require(config.path.project + '/' + config.path.symlinkDirectoryName + '/' +config.path.userConfigFile)`

And then to create the sprite, you just need to run `grunt sprite` and not `grunt sprite:<theme>`

@ezequielalba You may try it as long as the configuration in `magekey/grunt-sprite/grunt-sprite-config.json` is correct.

**Comment by tigerofasia** [comment]
It's a nice extension. Thanks for this @magekey !

**Comment by magekey** [comment]
@tigerofasia 
Thank you for your investigation.
Seems the description little confused.
`grunt setup` command should create a convenient symlink and copy `grunt-sprite-config.json.sample` to the root of the project. So you should modify this one, not a sample file under vendor directory.

But I'm glad that you solved the problem. Thank you.

**Comment by ezequielalba** [comment]
Thank you @tigerofasia and @magekey ! I will implement this on my next Development.
